steps:
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']

  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend']

  # Set IAM policy binding for Cloud Build to act as the service account
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['projects', 'add-iam-policy-binding', '$PROJECT_ID', '--member=serviceAccount:cloudrun-platherbs@plantherbs.iam.gserviceaccount.com', '--role=roles/run.invoker']

  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'backend', '--image', 'gcr.io/$PROJECT_ID/backend', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images:
- 'gcr.io/$PROJECT_ID/backend'
