step: 
  #build the container image
- name: 'gcr.io/plantherbs/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']
 #push the container image to Cotainer Registry
- name: 'gcr.io/plantherbs/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend']
  # Deploy container image to Cloud Run
- name: 'gcr.io/plantherbs/gcloud'
  args: ['beta',
  'run',
  'deploy',
  'backend',
  '--image',
  'gcr.io/$PROJECT_ID/backend',
  '--region',
  'asia-southeast2',
  '--platform',
  'managed',
  '--allow-unautenticated']

images:
  gcr.io/$PROJECT_ID/backend